### PR TITLE
Add WorkflowSwiftUI to Package.swift

### PR DESCRIPTION
**Pull request by MichaelOdere**
## Checklist

- [x] Unit Tests
- [x] UI Tests
- [x] Snapshot Tests (iOS only)
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by dhavalshreyas — APPROVED** [review]
Thanks @MichaelOdere!

**Comment by dhavalshreyas** [comment]
If you pull from latest master, it should have the fixes needed for CI.

**Comment by MichaelOdere** [comment]
Hi @dhavalshreyas! As far as I can tell my branch is up to date with main. The last commit I see in main is 5cf1fc705186da398289986e8e2ed01c32224bf2 and I have that in my branch. Can you help me to see what I'm missing?

**Comment by dhavalshreyas** [comment]
@MichaelOdere : Oops, fixing it [here](https://github.com/square/workflow-swift/pull/87).

**Comment by dhavalshreyas** [comment]
The fix has been merged, if you rebase on top of the fix, this should be good to go.

**Comment by MichaelOdere** [comment]
Everything has passed. Thanks @dhavalshreyas!

**Comment by dhavalshreyas** [comment]
Thanks @MichaelOdere!

**Pull request merged**
