### PR TITLE
[gardening]: swiftformat – prefer acl's on declarations

### PR DESCRIPTION
**Pull request by jamieQ**
changing the lint preference for this repo from having ACLs on extensions to declarations. this just changes the config – i did not run it against the repo yet.

### CODE REVIEW

**Comment by watt** [comment]
Worth syncing up with Register? Or do we want a unique set of rules here?

**Comment by jamieQ** [comment]
> Worth syncing up with Register? Or do we want a unique set of rules here?

personally i prefer this rule, so would be in favor of adopting universally. since we manage things independently here though i think it's fine to proceed with this without blocking on anyone's having stronger opinions about a larger change. i can float the proposed change to see what people think.

**Comment by watt** [comment]
> > Worth syncing up with Register? Or do we want a unique set of rules here?
> 
> personally i prefer this rule, so would be in favor of adopting universally. since we manage things independently here though i think it's fine to proceed with this without blocking on anyone's having stronger opinions about a larger change. i can float the proposed change to see what people think.

It's already present there, just I'm questioning whether we should be maintaining a separate config file in general.

**Review by g-mark — COMMENTED** [review]
_Thank You_

**Comment by jamieQ** [comment]
> It's already present there, just I'm questioning whether we should be maintaining a separate config file in general.

**Comment by jamieQ** [comment]
> It's already present there, just I'm questioning whether we should be maintaining a separate config file in general.

ah i see, thanks for elaborating. yeah having bifurcation here doesn't make sense to me – i'll copy over the config as best it can be.

**Comment by jamieQ** [comment]
actually it looks to me like this specific rule is _not_ yet enabled in register, so will plan to merge this before looking into a broader synchronization effort

**Review by g-mark — APPROVED** [review]

**Pull request merged**
